<?php

declare(strict_types=1);

return [
    'PT' => 'Portugal',
    'ES' => 'Spain',
    'FR' => 'France',
    'DE' => 'Germany',
    'IT' => 'Italy',
    'GB' => 'United Kingdom',
    'IE' => 'Ireland',
    'US' => 'United States',
    'CA' => 'Canada',
    'BR' => 'Brazil',
    'MX' => 'Mexico',
    'AR' => 'Argentina',
    'AO' => 'Angola',
    'MZ' => 'Mozambique',
    'CV' => 'Cape Verde',
    'NL' => 'Netherlands',
    'BE' => 'Belgium',
    'CH' => 'Switzerland',
    'AT' => 'Austria',
    'PL' => 'Poland',
    'SE' => 'Sweden',
    'NO' => 'Norway',
    'DK' => 'Denmark',
    'FI' => 'Finland',
    'GR' => 'Greece',
    'TR' => 'Turkey',
    'IN' => 'India',
    'CN' => 'China',
    'JP' => 'Japan',
    'AU' => 'Australia',
    'NZ' => 'New Zealand',
    'ZA' => 'South Africa',
    'OTHER' => 'Other',
];
